from __future__ import annotations

from obsidian_export.markdown import GENERATED_MARKER, yaml_frontmatter


def render_dashboard_notes() -> dict[str, str]:
    frontmatter = {
        "type": "dashboard",
        "source": "memetraderpro",
        "generated_by": "memetraderpro",
    }
    body = """# MemeTraderPro Intelligence Dashboard

GENERATED BY MEMETRADERPRO - DO NOT EDIT BELOW THIS LINE

## Command Layer

- [[MemeTraderPro Research Command Center]]
- [[MemeTraderPro Anomaly Radar]]
- [[MemeTraderPro Drift Monitor]]
- [[MemeTraderPro Signal Lineage]]
- [[MemeTraderPro Daily Workflow]]
- [[Top Wallets]]
- [[Wallets Pending Review]]
- [[Rug Association Watchlist]]
- [[Rejected Signal Winners]]
- [[Recent Paper Trade Outcomes]]

## Top Wallets By Confidence

Open [[Top Wallets]].

## Pending Review Wallets

Open [[Wallets Pending Review]].

## Wallet Candidate Audit Queue

```dataview
TABLE recommendation_action, audit_status, known_outcomes, source_coverage, promotion_score, demotion_score
FROM "MemeTraderPro/WalletCandidateReviews"
WHERE type = "wallet_candidate_review" AND review_resolved != true
SORT recommendation_action DESC, known_outcomes DESC
LIMIT 50
```

## High Rug Association

Open [[Rug Association Watchlist]].

## Recent Rejected Signals

Open [[Rejected Signal Winners]] first. Raw rejected-signal detail is intentionally excluded from Obsidian's live index.

## Recent Paper Trades

Open [[Recent Paper Trade Outcomes]].

## Recent Postmortems

```dataview
TABLE generated_at, token_mint, status, paper_lane, classifications
FROM "MemeTraderPro/Postmortems"
WHERE type = "postmortem"
SORT generated_at DESC
LIMIT 50
```
"""
    return {
        "Dashboards/MemeTraderPro Intelligence Dashboard.md": f"{yaml_frontmatter(frontmatter)}\n\n{body.rstrip()}\n"
    }
