from __future__ import annotations

from obsidian_export.markdown import GENERATED_MARKER, yaml_frontmatter


def render_dashboard_notes() -> dict[str, str]:
    frontmatter = {
        "type": "dashboard",
        "source": "memetraderpro",
        "generated_by": "memetraderpro",
    }
    body = """# MemeTraderPro Intelligence Dashboard

GENERATED BY MEMETRADERPRO - DO NOT EDIT BELOW THIS LINE

## Top Wallets By Confidence

```dataview
TABLE confidence_score, roi, win_rate, runner_count, rug_count, last_seen
FROM "MemeTraderPro/Wallets"
WHERE type = "wallet"
SORT confidence_score DESC
LIMIT 25
```

## Pending Review Wallets

```dataview
TABLE status, confidence_score, roi, win_rate, last_seen
FROM "MemeTraderPro/Wallets"
WHERE type = "wallet" AND contains(["PROMOTION_REVIEW", "DEMOTION_REVIEW"], status)
SORT status ASC, confidence_score DESC
LIMIT 50
```

## Wallet Candidate Audit Queue

```dataview
TABLE recommendation_action, audit_status, known_outcomes, source_coverage, promotion_score, demotion_score
FROM "MemeTraderPro/WalletCandidateReviews"
WHERE type = "wallet_candidate_review" AND review_resolved != true
SORT recommendation_action DESC, known_outcomes DESC
LIMIT 50
```

## High Rug Association

```dataview
TABLE rug_count, runner_count, confidence_score, status
FROM "MemeTraderPro/Wallets"
WHERE type = "wallet" AND rug_count > 0
SORT rug_count DESC
LIMIT 50
```

## Recent Rejected Signals

```dataview
TABLE timestamp, rejection_reason, lane, outcome_status
FROM "MemeTraderPro/RejectedSignals"
WHERE type = "rejected_signal"
SORT timestamp DESC
LIMIT 50
```

## Recent Paper Trades

```dataview
TABLE opened_at, closed_at, status, pnl, pnl_pct, paper_lane
FROM "MemeTraderPro/PaperTrades"
WHERE type = "paper_trade"
SORT opened_at DESC
LIMIT 50
```

## Recent Postmortems

```dataview
TABLE generated_at, token_mint, status, paper_lane, classifications
FROM "MemeTraderPro/Postmortems"
WHERE type = "postmortem"
SORT generated_at DESC
LIMIT 50
```
"""
    return {
        "Dashboards/MemeTraderPro Intelligence Dashboard.md": f"{yaml_frontmatter(frontmatter)}\n\n{body.rstrip()}\n"
    }
