import tempfile
import unittest
from pathlib import Path

from obsidian_export.dashboard_notes import render_dashboard_notes
from obsidian_export.candidate_note import render_wallet_candidate_note, wallet_candidate_filename
from obsidian_export.exporter import GENERATED_MARKER, merge_generated_note
from obsidian_export.signal_note import render_signal_note
from obsidian_export.wallet_note import render_wallet_note, wallet_filename


class ObsidianExportTests(unittest.TestCase):
    def test_wallet_note_has_frontmatter_metrics_links_and_marker(self):
        row = {
            "wallet": "WalletABC123",
            "tier": "paper_watch",
            "paper_watch_total_pnl": 12.5,
            "paper_watch_win_rate": 66.67,
            "avg_hold_seconds": 91.2,
            "behavior_profile": {
                "participation_frequency_in_runners": 3,
                "participation_frequency_in_rugs": 1,
            },
            "behavior_score": {"score": 78.2},
            "recommendation": {"action": "PROMOTION_REVIEW", "reasons": ["positive expectancy"]},
            "wallet_relationships": {"related_wallets": ["WalletRelated999"]},
            "last_seen": 1778770000.0,
        }
        note = render_wallet_note(
            row,
            recent_signals=[{"mint": "MintA", "score": 71, "signal_type": "cluster"}],
            postmortems=[{"postmortem_id": "pm_abc", "mint": "MintA"}],
        )

        self.assertTrue(note.startswith("---\n"))
        self.assertIn("type: wallet", note)
        self.assertIn("wallet_address: WalletABC123", note)
        self.assertIn("runner_count: 3", note)
        self.assertIn("rug_count: 1", note)
        self.assertIn("confidence_score: 78.2", note)
        self.assertIn(GENERATED_MARKER, note)
        self.assertIn("[[WAL-WalletRelated999]]", note)
        self.assertIn("[[PM-pm_abc]]", note)

    def test_wallet_filename_is_stable_and_obsidian_safe(self):
        self.assertEqual(wallet_filename("Wallet/ABC 123"), "WAL-Wallet-ABC-123.md")

    def test_signal_note_includes_market_risk_decision_and_wallet_links(self):
        note = render_signal_note(
            {
                "captured_at": 1778770000.0,
                "mint": "MintABC",
                "decision_id": "dec_123",
                "signal_type": "cluster",
                "paper_lane": "wallet_main",
                "should_trade": False,
                "triggering_wallets": [{"wallet": "WalletABC123"}],
                "market": {"liquidity": 12000, "market_cap": 40000, "token_age_seconds": 90},
                "risk": {"risk_label": "MEDIUM_RISK", "hard_block": False},
                "scoring": {"score": 64, "threshold": 68, "reasons_tail": ["score below threshold"]},
            }
        )

        self.assertIn("type: signal", note)
        self.assertIn("token_mint: MintABC", note)
        self.assertIn("liquidity: 12000.0", note)
        self.assertIn("decision: skip", note)
        self.assertIn("[[WAL-WalletABC123|WalletABC123]]", note)
        self.assertIn("score below threshold", note)

    def test_merge_generated_note_preserves_manual_notes_above_marker(self):
        existing = """---
type: wallet
wallet_address: old
---

Manual thesis that should stay.

GENERATED BY MEMETRADERPRO - DO NOT EDIT BELOW THIS LINE

old generated body
"""
        updated = merge_generated_note(
            existing,
            {"type": "wallet", "wallet_address": "WalletABC123"},
            "new generated body",
        )

        self.assertIn("Manual thesis that should stay.", updated)
        self.assertIn("wallet_address: WalletABC123", updated)
        self.assertIn("new generated body", updated)
        self.assertNotIn("old generated body", updated)

    def test_merge_generated_note_keeps_generated_title_after_marker(self):
        updated = merge_generated_note(
            None,
            {"type": "wallet"},
            "# Wallet WalletABC123\n\nGENERATED BY MEMETRADERPRO - DO NOT EDIT BELOW THIS LINE\n\n## Behavior Summary",
        )

        self.assertIn("GENERATED BY MEMETRADERPRO - DO NOT EDIT BELOW THIS LINE\n\n# Wallet WalletABC123", updated)

    def test_dashboard_notes_include_required_dataview_queries(self):
        notes = render_dashboard_notes()
        index = notes["Dashboards/MemeTraderPro Intelligence Dashboard.md"]

        self.assertIn("Top Wallets By Confidence", index)
        self.assertIn("Wallet Candidate Audit Queue", index)
        self.assertIn('FROM "MemeTraderPro/WalletCandidateReviews"', index)
        self.assertIn('FROM "MemeTraderPro/Wallets"', index)
        self.assertIn("Pending Review Wallets", index)
        self.assertIn("High Rug Association", index)
        self.assertIn("Recent Rejected Signals", index)
        self.assertIn("Recent Paper Trades", index)
        self.assertIn("Recent Postmortems", index)

    def test_exporter_writes_under_meme_trader_pro_folder(self):
        from obsidian_export.config import ObsidianExportConfig
        from obsidian_export.exporter import ObsidianExporter

        with tempfile.TemporaryDirectory() as tmp:
            exporter = ObsidianExporter(ObsidianExportConfig(vault_path=Path(tmp)))
            path = exporter.write_note(
                "Wallets/WAL-WalletABC123.md",
                {"type": "wallet", "wallet_address": "WalletABC123"},
                "generated",
            )

            self.assertEqual(
                path,
                Path(tmp) / "MemeTraderPro" / "Wallets" / "WAL-WalletABC123.md",
            )
            self.assertTrue(path.exists())

    def test_wallet_candidate_note_exposes_review_gates_and_links_wallet(self):
        candidate = {
            "wallet": "WalletABC123",
            "recommendation_action": "PROMOTION_REVIEW",
            "audit_status": "HUMAN_REVIEW_REQUIRED",
            "review_only": True,
            "wallet_list_apply_allowed": False,
            "comparison_status": "LEDGER_STRONGER_SIGNAL",
            "evidence_gates": {
                "known_outcome_sample_passed": True,
                "minimum_known_outcomes": 20,
                "source_coverage": 0.86,
            },
            "evidence": {
                "total_signals": 28,
                "known_outcomes": 24,
                "runner_participation": 14,
                "rug_participation": 0,
                "dead_participation": 2,
                "runner_participation_rate": 0.58,
                "rug_participation_rate": 0.0,
                "average_pnl_after_signal": 74.2,
                "promotion_score": 94.5,
                "demotion_score": 0,
                "recommendation_reasons": ["runner-heavy known outcomes"],
            },
            "audit_notes": ["review recommendation has enough known outcomes for human audit"],
        }

        note = render_wallet_candidate_note(candidate)

        self.assertEqual(wallet_candidate_filename(candidate), "WREV-PROMOTION_REVIEW-WalletABC123.md")
        self.assertIn("type: wallet_candidate_review", note)
        self.assertIn("wallet_address: WalletABC123", note)
        self.assertIn("recommendation_action: PROMOTION_REVIEW", note)
        self.assertIn("wallet_list_apply_allowed: false", note)
        self.assertIn("[[WAL-WalletABC123|WalletABC123]]", note)
        self.assertIn("runner-heavy known outcomes", note)
        self.assertIn("review recommendation has enough known outcomes", note)


if __name__ == "__main__":
    unittest.main()
