import tempfile
import unittest
import json
from pathlib import Path

from obsidian_export.dashboard_notes import render_dashboard_notes
from obsidian_export.candidate_note import render_wallet_candidate_note, wallet_candidate_filename
from obsidian_export.decision_note import render_wallet_review_decisions_note
from obsidian_export.exporter import GENERATED_MARKER, ensure_vault_ignore_filters, merge_generated_note
from obsidian_export.intelligence_notes import render_intelligence_notes
from obsidian_export.signal_note import render_signal_note
from obsidian_export.summary_notes import render_summary_index_notes
from obsidian_export.wallet_note import render_wallet_note, wallet_filename


class ObsidianExportTests(unittest.TestCase):
    def test_wallet_note_has_frontmatter_metrics_links_and_marker(self):
        row = {
            "wallet": "WalletABC123",
            "tier": "paper_watch",
            "paper_watch_total_pnl": 12.5,
            "paper_watch_win_rate": 66.67,
            "avg_hold_seconds": 91.2,
            "behavior_profile": {
                "participation_frequency_in_runners": 3,
                "participation_frequency_in_rugs": 1,
            },
            "behavior_score": {"score": 78.2},
            "recommendation": {"action": "PROMOTION_REVIEW", "reasons": ["positive expectancy"]},
            "wallet_relationships": {"related_wallets": ["WalletRelated999"]},
            "last_seen": 1778770000.0,
        }
        note = render_wallet_note(
            row,
            recent_signals=[{"mint": "MintA", "score": 71, "signal_type": "cluster"}],
            postmortems=[{"postmortem_id": "pm_abc", "mint": "MintA"}],
        )

        self.assertTrue(note.startswith("---\n"))
        self.assertIn("type: wallet", note)
        self.assertIn("wallet_address: WalletABC123", note)
        self.assertIn("runner_count: 3", note)
        self.assertIn("rug_count: 1", note)
        self.assertIn("confidence_score: 78.2", note)
        self.assertIn(GENERATED_MARKER, note)
        self.assertIn("[[WAL-WalletRelated999]]", note)
        self.assertIn("[[PM-pm_abc]]", note)

    def test_wallet_filename_is_stable_and_obsidian_safe(self):
        self.assertEqual(wallet_filename("Wallet/ABC 123"), "WAL-Wallet-ABC-123.md")

    def test_signal_note_includes_market_risk_decision_and_wallet_links(self):
        note = render_signal_note(
            {
                "captured_at": 1778770000.0,
                "mint": "MintABC",
                "decision_id": "dec_123",
                "signal_type": "cluster",
                "paper_lane": "wallet_main",
                "should_trade": False,
                "triggering_wallets": [{"wallet": "WalletABC123"}],
                "market": {"liquidity": 12000, "market_cap": 40000, "token_age_seconds": 90},
                "risk": {"risk_label": "MEDIUM_RISK", "hard_block": False},
                "scoring": {"score": 64, "threshold": 68, "reasons_tail": ["score below threshold"]},
            }
        )

        self.assertIn("type: signal", note)
        self.assertIn("token_mint: MintABC", note)
        self.assertIn("liquidity: 12000.0", note)
        self.assertIn("decision: skip", note)
        self.assertIn("[[WAL-WalletABC123|WalletABC123]]", note)
        self.assertIn("score below threshold", note)

    def test_merge_generated_note_preserves_manual_notes_above_marker(self):
        existing = """---
type: wallet
wallet_address: old
---

Manual thesis that should stay.

GENERATED BY MEMETRADERPRO - DO NOT EDIT BELOW THIS LINE

old generated body
"""
        updated = merge_generated_note(
            existing,
            {"type": "wallet", "wallet_address": "WalletABC123"},
            "new generated body",
        )

        self.assertIn("Manual thesis that should stay.", updated)
        self.assertIn("wallet_address: WalletABC123", updated)
        self.assertIn("new generated body", updated)
        self.assertNotIn("old generated body", updated)

    def test_merge_generated_note_keeps_generated_title_after_marker(self):
        updated = merge_generated_note(
            None,
            {"type": "wallet"},
            "# Wallet WalletABC123\n\nGENERATED BY MEMETRADERPRO - DO NOT EDIT BELOW THIS LINE\n\n## Behavior Summary",
        )

        self.assertIn("GENERATED BY MEMETRADERPRO - DO NOT EDIT BELOW THIS LINE\n\n# Wallet WalletABC123", updated)

    def test_dashboard_notes_include_required_dataview_queries(self):
        notes = render_dashboard_notes()
        index = notes["Dashboards/MemeTraderPro Intelligence Dashboard.md"]

        self.assertIn("Top Wallets By Confidence", index)
        self.assertIn("Wallet Candidate Audit Queue", index)
        self.assertIn('FROM "MemeTraderPro/WalletCandidateReviews"', index)
        self.assertIn("evidence_source", index)
        self.assertIn("round_trip_lifecycles", index)
        self.assertIn("review_resolved != true", index)
        self.assertNotIn('FROM "MemeTraderPro/Wallets"', index)
        self.assertNotIn('FROM "MemeTraderPro/RejectedSignals"', index)
        self.assertIn("Pending Review Wallets", index)
        self.assertIn("High Rug Association", index)
        self.assertIn("Recent Rejected Signals", index)
        self.assertIn("Recent Paper Trades", index)
        self.assertIn("Recent Postmortems", index)

    def test_wallet_candidate_note_surfaces_stage4_evidence(self):
        from obsidian_export.candidate_note import render_wallet_candidate_note

        note = render_wallet_candidate_note({
            "wallet": "WalletStage4",
            "recommendation_action": "DEMOTION_REVIEW",
            "audit_status": "HUMAN_REVIEW_REQUIRED",
            "review_resolved": False,
            "comparison_status": "STAGE4_REVIEW_GATE",
            "evidence_gates": {
                "known_outcome_sample_passed": True,
                "minimum_known_outcomes": 20,
                "minimum_round_trips": 3,
                "stage4_action": "DEMOTION_OR_BLOCK_REVIEW",
            },
            "evidence": {
                "source": "wallet_stage4_review",
                "known_outcomes": 20,
                "round_trip_lifecycles": 1,
                "rug_participation": 20,
                "runner_participation": 0,
                "source_bucket": "hold_no_edge",
                "scorecard_next_action": "hold_out_of_paper_watch",
            },
            "audit_notes": ["Stage 4 review gate produced a human-review action"],
        })

        self.assertIn("evidence_source: wallet_stage4_review", note)
        self.assertIn("stage4_action: DEMOTION_OR_BLOCK_REVIEW", note)
        self.assertIn("round_trip_lifecycles: 1", note)
        self.assertIn("Source", note)
        self.assertIn("wallet_stage4_review", note)
        self.assertIn("Round-trip lifecycles", note)
        self.assertIn("Stage 4 action", note)

    def test_exporter_writes_under_meme_trader_pro_folder(self):
        from obsidian_export.config import ObsidianExportConfig
        from obsidian_export.exporter import ObsidianExporter

        with tempfile.TemporaryDirectory() as tmp:
            exporter = ObsidianExporter(ObsidianExportConfig(vault_path=Path(tmp)))
            path = exporter.write_note(
                "Wallets/WAL-WalletABC123.md",
                {"type": "wallet", "wallet_address": "WalletABC123"},
                "generated",
            )

            self.assertEqual(
                path,
                Path(tmp) / "MemeTraderPro" / "Wallets" / "WAL-WalletABC123.md",
            )
            self.assertTrue(path.exists())

    def test_exporter_sets_ignore_filters_for_high_volume_generated_folders(self):
        with tempfile.TemporaryDirectory() as tmp:
            vault = Path(tmp)
            obsidian = vault / ".obsidian"
            obsidian.mkdir()
            (obsidian / "app.json").write_text(
                json.dumps({"alwaysUpdateLinks": True, "userIgnoreFilters": ["ExistingArchive/"]}),
                encoding="utf-8",
            )

            ensure_vault_ignore_filters(vault)

            settings = json.loads((obsidian / "app.json").read_text(encoding="utf-8"))
            self.assertTrue(settings["alwaysUpdateLinks"])
            self.assertIn("ExistingArchive/", settings["userIgnoreFilters"])
            self.assertIn("MemeTraderPro/Wallets/", settings["userIgnoreFilters"])
            self.assertIn("MemeTraderPro/RejectedSignals/", settings["userIgnoreFilters"])

    def test_summary_index_notes_are_static_and_focus_actionable_queues(self):
        notes = render_summary_index_notes(
            {
                "wallet_rows": [
                    {
                        "wallet": "WalletGOOD123",
                        "recommendation": {"action": "PROMOTION_REVIEW", "reasons": ["runner-heavy"]},
                        "behavior_score": {"score": 91.2},
                        "behavior_profile": {"wallet_roi": 18.5},
                        "paper_watch_win_rate": 80,
                        "runner_participation": 8,
                        "rug_participation": 0,
                        "last_seen": 1778770000.0,
                    },
                    {
                        "wallet": "WalletRUG999",
                        "recommendation": {"action": "DEMOTION_REVIEW", "reasons": ["rug-heavy"]},
                        "behavior_score": {"score": 12.0},
                        "behavior_profile": {"wallet_roi": -22.4},
                        "paper_watch_win_rate": 10,
                        "runner_participation": 1,
                        "rug_participation": 5,
                        "last_seen": 1778770100.0,
                    },
                ],
                "rejections": [
                    {
                        "decision_id": "dec_reject_win",
                        "mint": "MintWinner",
                        "lane": "wallet_main",
                        "rejection reason": "score_gate",
                        "recorded_at": 1778770200.0,
                        "what would have happened afterward if traded": {
                            "status": "runner",
                            "max_gain_pct": 312,
                        },
                    }
                ],
                "paper_trades": [
                    {
                        "decision_id": "dec_trade",
                        "token_mint": "MintTrade",
                        "status": "closed",
                        "paper_lane": "wallet_main",
                        "total_pnl": 4.2,
                        "total_pnl_pct": 21,
                        "entry_time": 1778770300.0,
                    }
                ],
            }
        )

        top_wallets = notes["Dashboards/Top Wallets.md"]
        rejected_winners = notes["Dashboards/Rejected Signal Winners.md"]
        trades = notes["Dashboards/Recent Paper Trade Outcomes.md"]

        self.assertIn("type: wallet_index", top_wallets)
        self.assertIn("WalletGOOD123", top_wallets)
        self.assertIn("WalletRUG999", notes["Dashboards/Rug Association Watchlist.md"])
        self.assertIn("MintWinner", rejected_winners)
        self.assertIn("runner", rejected_winners)
        self.assertIn("MintTrade", trades)
        for content in notes.values():
            self.assertNotIn("```dataview", content)

    def test_wallet_candidate_note_exposes_review_gates_and_links_wallet(self):
        candidate = {
            "wallet": "WalletABC123",
            "recommendation_action": "PROMOTION_REVIEW",
            "audit_status": "HUMAN_REVIEW_REQUIRED",
            "review_only": True,
            "wallet_list_apply_allowed": False,
            "comparison_status": "LEDGER_STRONGER_SIGNAL",
            "evidence_gates": {
                "known_outcome_sample_passed": True,
                "minimum_known_outcomes": 20,
                "source_coverage": 0.86,
            },
            "evidence": {
                "total_signals": 28,
                "known_outcomes": 24,
                "runner_participation": 14,
                "rug_participation": 0,
                "dead_participation": 2,
                "runner_participation_rate": 0.58,
                "rug_participation_rate": 0.0,
                "average_pnl_after_signal": 74.2,
                "promotion_score": 94.5,
                "demotion_score": 0,
                "recommendation_reasons": ["runner-heavy known outcomes"],
            },
            "audit_notes": ["review recommendation has enough known outcomes for human audit"],
        }

        note = render_wallet_candidate_note(candidate)

        self.assertEqual(wallet_candidate_filename(candidate), "WREV-PROMOTION_REVIEW-WalletABC123.md")
        self.assertIn("type: wallet_candidate_review", note)
        self.assertIn("wallet_address: WalletABC123", note)
        self.assertIn("recommendation_action: PROMOTION_REVIEW", note)
        self.assertIn("wallet_list_apply_allowed: false", note)
        self.assertIn("[[WAL-WalletABC123|WalletABC123]]", note)
        self.assertIn("runner-heavy known outcomes", note)
        self.assertIn("review recommendation has enough known outcomes", note)

    def test_wallet_candidate_note_marks_resolved_reviews(self):
        candidate = {
            "wallet": "WalletABC123",
            "recommendation_action": "PROMOTION_REVIEW",
            "audit_status": "RESOLVED_APPLIED",
            "review_resolved": True,
            "resolution": {
                "decision": "approve_promotion",
                "reason": "wallet is already tracked after approved apply",
            },
            "evidence_gates": {"known_outcome_sample_passed": True},
            "evidence": {"known_outcomes": 24},
        }

        note = render_wallet_candidate_note(candidate)

        self.assertIn("review_resolved: true", note)
        self.assertIn("audit_status: RESOLVED_APPLIED", note)
        self.assertIn("Resolved: True", note)
        self.assertIn("approve_promotion", note)

    def test_wallet_review_decisions_note_summarizes_saved_operator_decisions(self):
        note = render_wallet_review_decisions_note(
            {
                "decisions": [
                    {
                        "wallet": "WalletABC123",
                        "decision": "approve_promotion",
                        "approved": True,
                        "note": "repeat winner",
                        "approved_by": "operator",
                        "approved_at": 1778770000.0,
                    },
                    {
                        "wallet": "WalletBAD999",
                        "decision": "reject",
                        "approved": False,
                        "note": "weak evidence",
                        "approved_by": "operator",
                        "approved_at": 1778770100.0,
                    },
                ]
            },
            candidate_audit={
                "candidates": [
                    {
                        "wallet": "WalletABC123",
                        "recommendation_action": "PROMOTION_REVIEW",
                        "audit_status": "HUMAN_REVIEW_REQUIRED",
                    }
                ]
            },
        )

        self.assertIn("type: wallet_review_decisions", note)
        self.assertIn("approved_decisions: 1", note)
        self.assertIn("[[WAL-WalletABC123|WalletABC123]]", note)
        self.assertIn("[[WREV-PROMOTION_REVIEW-WalletABC123|candidate review]]", note)
        self.assertIn("approve_promotion", note)
        self.assertIn("repeat winner", note)
        self.assertIn("not_in_current_candidate_audit", note)

    def test_intelligence_notes_surface_anomalies_drift_lineage_and_workflow(self):
        notes = render_intelligence_notes(
            {
                "wallet_rows": [
                    {
                        "wallet": "WalletBAD999",
                        "recommendation": {"action": "DEMOTION_REVIEW"},
                        "behavior_score": {"score": 18},
                        "behavior_profile": {"wallet_roi": -12.5},
                        "rug_participation": 4,
                        "runner_participation": 1,
                        "signal_count": 44,
                    }
                ],
                "rejections": [
                    {
                        "decision_id": "dec_reject_win",
                        "mint": "MintWinner",
                        "rejection reason": "score_gate",
                        "what would have happened afterward if traded": {"status": "runner", "max_gain_pct": 300},
                    }
                ],
                "postmortems": [{"postmortem_id": "pm_open", "status": "open", "mint": "MintBad"}],
                "wallet_candidate_audit": {
                    "candidates": [
                        {
                            "wallet": "WalletNEW123",
                            "recommendation_action": "PROMOTION_REVIEW",
                            "audit_status": "HUMAN_REVIEW_REQUIRED",
                            "evidence": {"known_outcomes": 30, "promotion_score": 90},
                        }
                    ]
                },
                "replay_visibility": {"counts": {"records": 5}, "mode": "REVIEW_ONLY"},
                "wallet_replay_review": {
                    "summary": {"reviewable_wallets": 2, "low_coverage_wallets": 7, "co_entry_pairs": 3},
                    "operator_report_markdown": "# Wallet Replay Ecosystem Review\n\nReview-only.\n\n## Reviewable Wallets\n\n- `WalletGOOD`",
                },
                "wallet_cycle_report": {
                    "counts": {
                        "tracked_wallets": 523,
                        "active_paper_watch_wallets": 12175,
                        "blocked_paper_watch_wallets": 10,
                        "bad_wallets": 10,
                    },
                    "review_queue": {"promotion_review": 0, "demotion_review": 5},
                    "attention": ["demotion_reviews_pending"],
                },
                "wallet_candidate_quality_report": {
                    "summary": {
                        "active_candidates": 2659,
                        "blocked_candidates": 15,
                        "strong_observation": 4,
                        "paper_watch_review": 42,
                        "hold_review": 1200,
                        "reject_review": 1413,
                    },
                    "ranked_candidates": [
                        {
                            "wallet": "WalletQUALITY123",
                            "quality_score": 84.5,
                            "recommended_observation": "STRONG_OBSERVATION",
                            "winner_mints": 4,
                            "early_buy_events": 18,
                            "risk_flags": [],
                        }
                    ],
                },
                "wallet_candidate_quality_review": {
                    "summary": {
                        "total_reviewed": 50,
                        "promotion_review_ready": 2,
                        "observe_more": 47,
                        "risk_review": 1,
                        "reject_review": 0,
                    },
                    "shortlist": [
                        {
                            "wallet": "WalletREADY456",
                            "quality_score": 88,
                            "recommendation": {"action": "PROMOTION_REVIEW_READY"},
                            "evidence_gaps": [],
                        }
                    ],
                },
                "wallet_candidate_evidence_plan": {
                    "summary": {
                        "total_candidates": 50,
                        "ready_for_review": 0,
                        "needs_replay_coverage": 44,
                        "needs_outcome_coverage": 44,
                        "risk_review": 6,
                    },
                    "coverage_queue": [
                        {
                            "wallet": "WalletPLAN789",
                            "priority_score": 61.5,
                            "next_action": "COLLECT_REPLAY_AND_OUTCOME_EVIDENCE",
                            "missing": {"replay_known_15m": 7, "fillable_events": 8, "known_outcomes": 6},
                        }
                    ],
                },
                "wallet_candidate_backfill_targets": {
                    "summary": {
                        "total_targets": 50,
                        "needs_wallet_history": 34,
                        "needs_outcome_label_backfill": 10,
                        "needs_more_replay_events": 0,
                        "risk_review": 6,
                    },
                    "targets": [
                        {
                            "wallet": "WalletBACKFILL123",
                            "priority_score": 58.5,
                            "next_collection_step": "COLLECT_WALLET_HISTORY",
                            "local_replay_events": 0,
                            "unknown_15m_events": 0,
                            "missing": {"replay_known_15m": 10, "fillable_events": 10, "known_outcomes": 10},
                        }
                    ],
                },
                "wallet_history_backfill": {
                    "summary": {
                        "wallets_processed": 45,
                        "wallets_successfully_backfilled": 12,
                        "wallets_partially_backfilled": 5,
                        "wallets_blocked": 3,
                        "total_evidence_rows_created": 84,
                        "ready_for_candidate_review": 2,
                    },
                    "wallets": [
                        {
                            "wallet": "WalletHISTORY456",
                            "status": "COLLECTED",
                            "target_status": "wallet_history_collected",
                            "evidence_rows_created": 8,
                            "metrics": {"evidence_confidence_score": 72.5},
                        }
                    ],
                },
                "wallet_evidence_enrichment": {
                    "summary": {
                        "total_evidence_rows": 84,
                        "enriched_rows": 22,
                        "missing_market_context_rows": 10,
                        "missing_outcome_label_rows": 52,
                        "rows_with_entry_context": 74,
                        "rows_with_known_outcome": 22,
                    },
                    "evidence_records": [
                        {
                            "wallet": "WalletENRICH789",
                            "token_mint": "MintENRICH",
                            "enrichment_status": "ENRICHED",
                            "observed_action": "buy",
                            "estimated_entry_context": {"price": 0.0012, "liquidity": 12000},
                            "later_token_outcome": {"outcome_type": "runner"},
                            "confidence_score": 90,
                        }
                    ],
                },
                "wallet_missing_market_context": {
                    "summary": {
                        "target_mints": 3,
                        "missing_market_context_rows": 10,
                        "wallets_affected": 7,
                        "targets_with_known_outcomes": 1,
                    },
                    "targets": [
                        {
                            "token_mint": "MintMISSINGCTX",
                            "next_collection_step": "BACKFILL_MARKET_CONTEXT",
                            "evidence_rows": 5,
                            "unique_wallets": 3,
                            "known_outcome_rows": 1,
                            "backfill_window": {"start_time": 1000, "end_time": 2000},
                        }
                    ],
                },
            }
        )

        command = notes["Dashboards/MemeTraderPro Research Command Center.md"]
        cycle = notes["Dashboards/Wallet Cycle Report.md"]
        quality = notes["Dashboards/Wallet Candidate Quality.md"]
        quality_review = notes["Dashboards/Wallet Candidate Quality Review.md"]
        evidence_plan = notes["Dashboards/Wallet Candidate Evidence Plan.md"]
        backfill_targets = notes["Dashboards/Wallet Candidate Backfill Targets.md"]
        wallet_history = notes["Dashboards/Wallet History Backfill.md"]
        evidence_enrichment = notes["Dashboards/Wallet Evidence Enrichment.md"]
        missing_context = notes["Dashboards/Wallet Missing Market Context.md"]
        replay = notes["Dashboards/Wallet Replay Ecosystem Review.md"]
        anomaly = notes["Dashboards/MemeTraderPro Anomaly Radar.md"]
        drift = notes["Dashboards/MemeTraderPro Drift Monitor.md"]
        lineage = notes["Dashboards/MemeTraderPro Signal Lineage.md"]
        workflow = notes["Dashboards/MemeTraderPro Daily Workflow.md"]
        shared = notes["../SharedQuant/Dashboards/Quant Research Command Center.md"]

        self.assertIn("Action Queue", command)
        self.assertIn("Wallet Degradation", anomaly)
        self.assertIn("WalletBAD999", anomaly)
        self.assertIn("Rejected-Signal Winners", anomaly)
        self.assertIn("MintWinner", anomaly)
        self.assertIn("Wallet-Score Drift", drift)
        self.assertIn("Signal Lineage", lineage)
        self.assertIn("Daily Research Workflow", workflow)
        self.assertIn("Wallet Replay Ecosystem Review", command)
        self.assertIn("Wallet Cycle Report", command)
        self.assertIn("Wallet Candidate Quality", command)
        self.assertIn("Wallet Candidate Quality Review", command)
        self.assertIn("Wallet Candidate Evidence Plan", command)
        self.assertIn("Wallet Candidate Backfill Targets", command)
        self.assertIn("Wallet History Backfill", command)
        self.assertIn("Wallet Evidence Enrichment", command)
        self.assertIn("Wallet Missing Market Context", command)
        self.assertIn("Tracked wallets", cycle)
        self.assertIn("12,175", cycle)
        self.assertIn("demotion_reviews_pending", cycle)
        self.assertIn("type: wallet_cycle_report", cycle)
        self.assertIn("type: wallet_candidate_quality_report", quality)
        self.assertIn("WalletQUALITY123", quality)
        self.assertIn("2,659", quality)
        self.assertIn("type: wallet_candidate_quality_review", quality_review)
        self.assertIn("WalletREADY456", quality_review)
        self.assertIn("PROMOTION_REVIEW_READY", quality_review)
        self.assertIn("type: wallet_candidate_evidence_plan", evidence_plan)
        self.assertIn("WalletPLAN789", evidence_plan)
        self.assertIn("COLLECT_REPLAY_AND_OUTCOME_EVIDENCE", evidence_plan)
        self.assertIn("type: wallet_candidate_backfill_targets", backfill_targets)
        self.assertIn("WalletBACKFILL123", backfill_targets)
        self.assertIn("COLLECT_WALLET_HISTORY", backfill_targets)
        self.assertIn("type: wallet_history_backfill", wallet_history)
        self.assertIn("WalletHISTORY456", wallet_history)
        self.assertIn("wallet_history_collected", wallet_history)
        self.assertIn("type: wallet_evidence_enrichment", evidence_enrichment)
        self.assertIn("WalletENRICH789", evidence_enrichment)
        self.assertIn("ENRICHED", evidence_enrichment)
        self.assertIn("type: wallet_missing_market_context", missing_context)
        self.assertIn("MintMISSINGCTX", missing_context)
        self.assertIn("BACKFILL_MARKET_CONTEXT", missing_context)
        self.assertIn("reviewable wallets: 2", command)
        self.assertIn("WalletGOOD", replay)
        self.assertIn("type: wallet_replay_ecosystem_review", replay)
        self.assertIn("Cross-Project Anomaly Radar", shared)
        self.assertIn("Prop API Dashboard", shared)
        self.assertIn("PropAPI/CoverageReports", shared)


if __name__ == "__main__":
    unittest.main()
