from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any


GENERATED_MARKER = "GENERATED BY MEMETRADERPRO - DO NOT EDIT BELOW THIS LINE"


def slugify(value: Any, *, max_length: int = 120) -> str:
    text = str(value or "unknown").strip()
    text = re.sub(r"[^A-Za-z0-9._-]+", "-", text)
    text = re.sub(r"-+", "-", text).strip("-._")
    if not text:
        text = "unknown"
    return text[:max_length].rstrip("-._") or "unknown"


def short_id(value: Any, *, head: int = 8, tail: int = 6) -> str:
    text = slugify(value, max_length=200)
    if len(text) <= head + tail + 1:
        return text
    return f"{text[:head]}-{text[-tail:]}"


def iso_from_ts(value: Any) -> str | None:
    try:
        if value in (None, ""):
            return None
        ts = float(value)
    except (TypeError, ValueError):
        return str(value) if value else None
    try:
        return datetime.fromtimestamp(ts, timezone.utc).isoformat()
    except (OverflowError, OSError, ValueError):
        return str(value)


def short_datetime(value: Any) -> str | None:
    text = iso_from_ts(value)
    if not text:
        return None
    text = text.replace("+00:00", "Z")
    if "T" not in text:
        return text
    return text[:16].replace("T", " ")


def compact_number(value: Any, digits: int = 4) -> Any:
    if value in (None, ""):
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return value
    if number != number:
        return None
    return round(number, digits)


def yaml_frontmatter(data: dict[str, Any]) -> str:
    lines = ["---"]
    for key, value in data.items():
        lines.extend(_yaml_lines(str(key), value))
    lines.append("---")
    return "\n".join(lines)


def _yaml_lines(key: str, value: Any) -> list[str]:
    if isinstance(value, list):
        if not value:
            return [f"{key}: []"]
        lines = [f"{key}:"]
        for item in value:
            lines.append(f"  - {_yaml_scalar(item)}")
        return lines
    if isinstance(value, dict):
        if not value:
            return [f"{key}: {{}}"]
        lines = [f"{key}:"]
        for sub_key, sub_value in value.items():
            lines.append(f"  {sub_key}: {_yaml_scalar(sub_value)}")
        return lines
    return [f"{key}: {_yaml_scalar(value)}"]


def _yaml_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if re.match(r"^[A-Za-z0-9_./:@+-]+$", text):
        return text
    return json.dumps(text, ensure_ascii=False)


def wikilink(stem: str, label: str | None = None) -> str:
    if label:
        return f"[[{stem}|{label}]]"
    return f"[[{stem}]]"


def bullet_list(items: list[Any], *, empty: str = "None recorded.") -> str:
    rows = [str(item) for item in items if item not in (None, "", [], {})]
    if not rows:
        return f"- {empty}"
    return "\n".join(f"- {row}" for row in rows)


def table(headers: list[str], rows: list[list[Any]]) -> str:
    clean_headers = [_table_cell(header) for header in headers]
    out = [
        "| " + " | ".join(clean_headers) + " |",
        "| " + " | ".join(["---"] * len(clean_headers)) + " |",
    ]
    for row in rows:
        cells = []
        for value in row:
            cells.append(_table_cell(value))
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def _table_cell(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("\n", " ").replace("|", "\\|")


def as_list(value: Any) -> list[Any]:
    if isinstance(value, list):
        return value
    if value in (None, ""):
        return []
    return [value]


def as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def first_present(*values: Any) -> Any:
    for value in values:
        if value not in (None, "", [], {}):
            return value
    return None
